# Generated by Django 4.0.2 on 2022-03-26 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ervingroup',
            name='custom_logo',
            field=models.FileField(blank=True, help_text='For what logo will be used for members in this group?', null=True, upload_to='', verbose_name='custom logo'),
        ),
    ]
