# Generated by Django 4.0.2 on 2022-03-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ervin', '0002_ervingroup_custom_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_logo', models.FileField(blank=True, help_text='What logo will be used for members in this group?', null=True, upload_to='', verbose_name='custom logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='ervingroup',
            name='custom_logo',
        ),
        migrations.AddField(
            model_name='ervingroup',
            name='company',
            field=models.ForeignKey(blank=True, help_text="What is this user's company", null=True, on_delete=django.db.models.deletion.SET_NULL, to='ervin.company'),
        ),
    ]
