# Generated by Django 4.0.2 on 2022-03-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervin', '0004_remove_ervingroup_company_ervinuser_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='name',
            field=models.CharField(default='', help_text='The company name', max_length=60, verbose_name='name'),
            preserve_default=False,
        ),
    ]
