# Generated by Django 4.0.2 on 2022-03-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervin', '0006_company_custom_page_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_header_image',
            field=models.FileField(blank=True, help_text='What header will be used for members in this group?', null=True, upload_to='', verbose_name='custom header image'),
        ),
        migrations.AddField(
            model_name='company',
            name='custom_page_subtitle',
            field=models.CharField(blank=True, help_text='The subtitle to be displayed on the home page', max_length=50, verbose_name='custom page subtitle'),
        ),
    ]
