# Generated by Django 4.0.2 on 2022-03-26 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ervin', '0007_company_custom_header_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='custom_colorscheme',
            field=models.CharField(blank=True, choices=[('blue', 'blue')], help_text='The color scheme to be used', max_length=20, verbose_name='custom color scheme'),
        ),
    ]
